on:
  release:
    types: [created, edited]
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  retag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: fischerscode/tagger@v0
        with:
          prefix: v
